---
title: "p8105_hw5_mjn2142"
author: "Matthew Neky"
date: "11/18/2021"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

### Problem 2

## Dataframe with All File Names

```{r}
long_study_data = as_tibble(list.files("./data"))
```

## Iterating over File Names

```{r}
long_study_output =
  map(.x = long_study_data, ~ read_csv(.x))

nest_long_study_data = 
  merge(long_study_data, long_study_output) %>% 
  nest(data = value.week_1:value.week_8)
```

## Tidying Data

```{r}
tidied_nest_data = nest_long_study_data %>% 
  separate(
    col = value,
    into = c("group", "id"),
    sep = "_"
  ) %>% 
  mutate(
  group = recode(
    group,
    "con" = "control",
    "exp" = "experimental"
  ),
   id = substr(id, start = 1, stop = 2)
  )
)
```

